ALTER TABLE users ADD COLUMN kdf_time INTEGER NOT NULL DEFAULT 3;
ALTER TABLE users ADD COLUMN kdf_memory INTEGER NOT NULL DEFAULT 65536;
ALTER TABLE users ADD COLUMN kdf_threads INTEGER NOT NULL DEFAULT 4;
